export const CHANGE_LOCATION_PATH = "CHANGE_LOCATION_PATH";

export const SET_USER_DATA = "SET_USER_DATA";

export const GET_ROOMS_GOMOKU = "GET_ROOMS_GOMOKU";
export const GET_ROOMS_BLOCK_HEAD = "GET_ROOMS_BLOCK_HEAD";
export const GET_ROOM_ID = "GET_ROOM_ID";

export const COUNT_GOMOKU_USER_PLAYING = "COUNT_GOMOKU_USER_PLAYING";
export const COUNT_BLOCK_HEAD_USER_PLAYING = "COUNT_BLOCK_HEAD_USER_PLAYING";

export const GET_SQUARE_POSITION = "GET_SQUARE_POSITION";
