export const CHANGE_ROUTE = "CHANGE_ROUTE";
export const SET_USER_INFO = "SET_USER_INFO";
export const GET_ROOMS_GOMOKU = "GET_ROOMS_GOMOKU";
export const GET_ROOMS_BLOCK_HEAD = "GET_ROOMS_BLOCK_HEAD";
