export const SET_USER_DATA = "SET_USER_DATA";
export const GET_SQUARE_POSITION = "GET_SQUARE_POSITION";

/**
 * Modal Types
 */
export const TOGGLE_FIND_ROOM_MODAL = "TOGGLE_FIND_ROOM_MODAL";
export const TOGGLE_WINNER_OR_LOST_MODAL = "TOGGLE_WINNER_OR_LOST_MODAL";

export const LOADING_OVERLAY = "LOADING_OVERLAY";
export const TOGGLE_DIALOG = "TOGGLE_DIALOG";

export const TOGGLE_USER_INFO_MODAL = "TOGGLE_USER_INFO_MODAL";
